// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sacrament_Planner.Data;

namespace Sacrament_Planner.Migrations
{
    [DbContext(typeof(MeetingContext))]
    [Migration("20200331032245_HymnPage")]
    partial class HymnPage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sacrament_Planner.Models.Hymns", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HymnName");

                    b.Property<int?>("MeetingsID");

                    b.Property<int>("PageNumber");

                    b.HasKey("ID");

                    b.HasIndex("MeetingsID");

                    b.ToTable("Hymn");
                });

            modelBuilder.Entity("Sacrament_Planner.Models.Meetings", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Conducting");

                    b.Property<string>("IntermediateMusicalNumber");

                    b.Property<int>("IntermediateSong");

                    b.Property<DateTime>("MeetingDate");

                    b.Property<string>("Presiding");

                    b.HasKey("ID");

                    b.ToTable("Meeting");
                });

            modelBuilder.Entity("Sacrament_Planner.Models.Members", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<string>("Calling");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsMale");

                    b.Property<string>("LastName");

                    b.Property<int?>("MeetingsID");

                    b.Property<int?>("MeetingsID1");

                    b.HasKey("ID");

                    b.HasIndex("MeetingsID");

                    b.HasIndex("MeetingsID1");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("Sacrament_Planner.Models.Hymns", b =>
                {
                    b.HasOne("Sacrament_Planner.Models.Meetings")
                        .WithMany("Hymns")
                        .HasForeignKey("MeetingsID");
                });

            modelBuilder.Entity("Sacrament_Planner.Models.Members", b =>
                {
                    b.HasOne("Sacrament_Planner.Models.Meetings")
                        .WithMany("Prayers")
                        .HasForeignKey("MeetingsID");

                    b.HasOne("Sacrament_Planner.Models.Meetings")
                        .WithMany("Speakers")
                        .HasForeignKey("MeetingsID1");
                });
#pragma warning restore 612, 618
        }
    }
}
